/** @type {import('xo').FlatXoConfig} */
const xoConfig = [
    {
        ignores: ['www/**', 'node_modules/**', 'xo.config.*', 'postcss.config.js'],
    },
    {
        space: 4,
        semicolon: true,
        files: ['lib/**/*.mjs', 'tests/**/*.mjs'],
        rules: {
            'camelcase': 'off',
            'capitalized-comments': 'off',
            'object-shorthand': 'off',
            'one-var': 'off',
            'prefer-destructuring': 'off',
            'no-warning-comments': 'off',
            'arrow-body-style': 'off',

            '@stylistic/object-curly-spacing': 'off',
            '@stylistic/quotes': 'off',
            '@stylistic/arrow-parens': 'off', // "(x) => x" is fine

            'unicorn/filename-case': 'off', // test-cm-dirtyflag.mjs fine
            'unicorn/no-array-callback-reference': 'off',
            'unicorn/prefer-spread': 'off',
            'unicorn/prevent-abbreviations': 'off',

            'unicorn/prefer-module': 'off', // TODO: We shouldn't really have this
            'unicorn/prefer-switch': 'off',
        },
    },
    {
        space: 4,
        semicolon: true,
        files: ['lib/**/*.js', 'tests/**/*.js', 'build/**/*.js'],
        languageOptions: {
            ecmaVersion: 2022,
            sourceType: 'commonjs',
            globals: {
                window: 'readonly',
                document: 'readonly',
                console: 'readonly',
                navigator: 'readonly',
                location: 'readonly',
                history: 'readonly',
                fetch: 'readonly',
                XMLHttpRequest: 'readonly',
                FormData: 'readonly',
                URL: 'readonly',
                URLSearchParams: 'readonly',
                Blob: 'readonly',
                File: 'readonly',
                FileReader: 'readonly',
                DOMParser: 'readonly',
                Worker: 'readonly',
                Proxy: 'readonly',
                crypto: 'readonly',
                Option: 'readonly',
                Image: 'readonly',
                Event: 'readonly',
                CustomEvent: 'readonly',
                HTMLElement: 'readonly',
                setTimeout: 'readonly',
                clearTimeout: 'readonly',
                setInterval: 'readonly',
                clearInterval: 'readonly',
                requestAnimationFrame: 'readonly',
                cancelAnimationFrame: 'readonly',
                getComputedStyle: 'readonly',
                process: 'readonly',
                require: 'readonly',
                module: 'readonly',
                exports: 'readonly',
                __dirname: 'readonly',
                __filename: 'readonly',
                Buffer: 'readonly',
            },
        },
        rules: {
            // Keep ES5-era style: var, function decls, snake_case, "use strict" pragmas.
            'arrow-body-style': 'off',
            'no-var': 'off',
            'prefer-const': 'off',
            'prefer-arrow-callback': 'off',
            'func-names': 'off',
            'func-name-matching': 'off',
            'camelcase': 'off',
            'object-shorthand': 'off',
            'prefer-template': 'off',
            'prefer-destructuring': 'off',
            'prefer-spread': 'off',
            'prefer-rest-params': 'off',
            'prefer-object-spread': 'off',
            'prefer-object-has-own': 'off',
            'logical-assignment-operators': 'off',
            'no-useless-concat': 'off',
            'vars-on-top': 'off',
            'one-var': 'off',
            'no-multi-assign': 'off',
            'strict': 'off',
            'no-implicit-coercion': 'off',
            'no-negated-condition': 'off',
            'capitalized-comments': 'off',
            'no-warning-comments': 'off',
            'no-multi-str': 'off',
            'no-eq-null': 'off',
            'no-unused-expressions': 'off',
            'no-useless-return': 'off',
            'no-useless-escape': 'off',
            'no-lonely-if': 'off',
            'no-alert': 'off',
            'dot-notation': 'off',
            'max-params': 'off',
            'max-nested-callbacks': 'off',
            'require-unicode-regexp': 'off',

            // Callback signatures often take args we don't use; don't force underscore rename.
            'no-unused-vars': ['error', {
                args: 'none',
                vars: 'all',
                ignoreRestSiblings: true,
                caughtErrors: 'none',
            }],

            // Stylistic rules: keep existing whitespace/quote/comma style.
            '@stylistic/quotes': 'off',
            '@stylistic/quote-props': 'off',
            '@stylistic/spaced-comment': 'off',
            '@stylistic/comma-dangle': 'off',
            '@stylistic/object-curly-spacing': 'off',
            '@stylistic/object-curly-newline': 'off',
            '@stylistic/array-bracket-spacing': 'off',
            '@stylistic/array-bracket-newline': 'off',
            '@stylistic/array-element-newline': 'off',
            '@stylistic/padding-line-between-statements': 'off',
            '@stylistic/padded-blocks': 'off',
            '@stylistic/no-multiple-empty-lines': 'off',
            '@stylistic/no-multi-spaces': 'off',
            '@stylistic/operator-linebreak': 'off',
            '@stylistic/function-paren-newline': 'off',
            '@stylistic/function-call-argument-newline': 'off',
            '@stylistic/curly-newline': 'off',
            '@stylistic/brace-style': 'off',
            '@stylistic/block-spacing': 'off',
            '@stylistic/one-var-declaration-per-line': 'off',
            '@stylistic/max-statements-per-line': 'off',
            '@stylistic/max-len': 'off',
            '@stylistic/indent-binary-ops': 'off',
            '@stylistic/indent': 'off',
            '@stylistic/key-spacing': 'off',
            '@stylistic/multiline-ternary': 'off',
            '@stylistic/no-mixed-operators': 'off',
            '@stylistic/lines-between-class-members': 'off',
            '@stylistic/dot-location': 'off',
            '@stylistic/newline-per-chained-call': 'off',
            '@stylistic/wrap-iife': 'off',
            '@stylistic/space-before-function-paren': 'off',
            '@stylistic/nonblock-statement-body-position': 'off',

            // unicorn: drop opinionated rewrites for code we don't want to modernise.
            'unicorn/prefer-module': 'off',
            'unicorn/prefer-node-protocol': 'off',
            'unicorn/prefer-global-this': 'off',
            'unicorn/prefer-string-replace-all': 'off',
            'unicorn/prefer-string-slice': 'off',
            'unicorn/prefer-string-starts-ends-with': 'off',
            'unicorn/prefer-string-raw': 'off',
            'unicorn/prefer-includes': 'off',
            'unicorn/prefer-array-some': 'off',
            'unicorn/prefer-array-find': 'off',
            'unicorn/prefer-spread': 'off',
            'unicorn/prefer-ternary': 'off',
            'unicorn/prefer-query-selector': 'off',
            'unicorn/prefer-dom-node-append': 'off',
            'unicorn/prefer-dom-node-remove': 'off',
            'unicorn/prefer-dom-node-text-content': 'off',
            'unicorn/prefer-dom-node-dataset': 'off',
            'unicorn/prefer-number-properties': 'off',
            'unicorn/prefer-math-trunc': 'off',
            'unicorn/prefer-optional-catch-binding': 'off',
            'unicorn/prefer-export-from': 'off',
            'unicorn/prefer-add-event-listener': 'off',
            'unicorn/prefer-reflect-apply': 'off',
            'unicorn/prefer-at': 'off',
            'unicorn/prefer-switch': 'off',
            'unicorn/prefer-top-level-await': 'off',
            'unicorn/prefer-structured-clone': 'off',
            'unicorn/prefer-array-flat': 'off',
            'unicorn/prefer-array-flat-map': 'off',
            'unicorn/prefer-set-has': 'off',
            'unicorn/prefer-regexp-test': 'off',
            'unicorn/prefer-logical-operator-over-ternary': 'off',
            'unicorn/prefer-prototype-methods': 'off',
            'unicorn/prefer-single-call': 'off',
            'unicorn/prefer-date-now': 'off',
            'unicorn/prefer-keyboard-event-key': 'off',
            'unicorn/no-array-for-each': 'off',
            'unicorn/no-array-callback-reference': 'off',
            'unicorn/no-array-reduce': 'off',
            'unicorn/no-array-sort': 'off',
            'unicorn/no-array-push-push': 'off',
            'unicorn/no-for-loop': 'off',
            'unicorn/no-null': 'off',
            'unicorn/no-this-assignment': 'off',
            'unicorn/no-negated-condition': 'off',
            'unicorn/no-lonely-if': 'off',
            'unicorn/no-useless-undefined': 'off',
            'unicorn/no-anonymous-default-export': 'off',
            'unicorn/no-empty-file': 'off',
            'unicorn/no-immediate-mutation': 'off',
            'unicorn/no-document-cookie': 'off',
            'unicorn/no-await-expression-member': 'off',
            'unicorn/no-process-exit': 'off',
            'unicorn/no-nested-ternary': 'off',
            'unicorn/empty-brace-spaces': 'off',
            'unicorn/consistent-function-scoping': 'off',
            'unicorn/explicit-length-check': 'off',
            'unicorn/filename-case': 'off',
            'unicorn/numeric-separators-style': 'off',
            'unicorn/prevent-abbreviations': 'off',
            'unicorn/catch-error-name': 'off',
            'unicorn/error-message': 'off',
            'unicorn/escape-case': 'off',
            'unicorn/throw-new-error': 'off',
            'unicorn/new-for-builtins': 'off',
            'unicorn/switch-case-braces': 'off',
            'unicorn/better-regex': 'off',
            'unicorn/text-encoding-identifier-case': 'off',
            'unicorn/no-instanceof-builtins': 'off',
            'unicorn/relative-url-style': 'off',

            // n plugin: not a node CLI app; many rules don't apply.
            'n/file-extension-in-import': 'off',
            'n/prefer-global/process': 'off',
            'n/prefer-promises/fs': 'off',
            'n/no-process-exit': 'off',
            'n/no-deprecated-api': 'off',
            'n/no-unsupported-features/node-builtins': 'off',

            // import-x: CommonJS, not ESM
            'import-x/extensions': 'off',
            'import-x/no-commonjs': 'off',
            'import-x/no-unassigned-import': 'off',
            'import-x/no-named-as-default-member': 'off',
            'import-x/order': 'off',
            'import-x/first': 'off',
            'import-x/newline-after-import': 'off',
        },
    },
    {
        // Must come after the `space: 4` block above: xo derives the indent
        // rules from `space` and writes them into the same config item,
        // overwriting any user-supplied disables. A later flat-config item
        // wins, so we re-disable them here. Existing code has creative
        // continuation indents that we don't want to chase.
        files: ['lib/**/*.js', 'tests/**/*.js', 'build/**/*.js'],
        rules: {
            '@stylistic/indent': 'off',
            '@stylistic/indent-binary-ops': 'off',
        },
    },
];

export default xoConfig;
