set -eu
DEPLOY_DIR="$(dirname $(readlink -f $0))"

# Generate main script. This will be run as root when install.sh is executed
cat <<EOF > "${DEPLOY_DIR}/deploy.sh"
# This file is generated by ${DEPLOY_DIR}/deploy.sh, do not alter
(cd ${DEPLOY_DIR}/.. && \
    sudo -u "${DB_SUDO_USER}" ./build.sh "${DB_NAME}" "${DB_USER}" "${DB_PASS}"; \
    ) || exit 1
EOF
