# https://github.github.io/actions-cheat-sheet/actions-cheat-sheet.html
# https://github.com/actions/checkout

on:
  push:
    branches:
      - '[0-9]+\.[0-9]+'
      - 'test'

name: Build documentation

jobs:
  int-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out CLiC
        # NB: Checks out into GITHUB_WORKSPACE, e.g. /home/runner/work/clic/clic
        uses: actions/checkout@v4
        with:
          # Get enough history so git describe works
          fetch-depth: 0
          fetch-tags: true
      - name: Make documentation
        run: make -C docs
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          external_repository: mahlberg-lab/user-guide.clic-fiction.com
          publish_branch: main
          publish_dir: ./docs/_build/
          destination_dir: ./${{ github.ref_name }}
