on:
#  push:
#    branches:
#      - '[0-9]+\.[0-9]+'
#    paths:
#      - flexiclic/build-wheels.sh
  workflow_dispatch:

name: build-wheels

jobs:
  build-wheels:
    runs-on: ubuntu-24.04
    name: Build FlexiConc wheels

    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Check out CLiC
        uses: actions/checkout@v4
      - name: Build wheels
        run: ./flexiclic/build-wheels.sh
      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: prebuild-wheels
          path: ./flexiclic/prebuilt
